name: Build a Docker image

# This workflow is triggered on pushes to the repository:
on: [push]

jobs:
  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          # We omit the "registry" parameter so it defaults to
          # DockerHub
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: dockerhub613/debian-package-docker
          tag_with_ref: true
          tag_with_sha: true

