name: Build Docker images

# This workflow is triggered on pushes to the repository:
on: [push, workflow_dispatch]

jobs:
  build_docker_images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Note that we use a DockerHub token to authenticate to
      # to DockerHub.
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: macrotex
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (unstable)
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            DEBIAN_DISTRIBUTION=unstable-slim
          tags: unstable,sid
